### ISSUE TITLE
Unable to load pretty formatter- loop

### ISSUE THREAD

**Issue by gituser-21** [cucumber/cucumber-js-pretty-formatter#1]
Hi @jbpros, @kozhevnikov  et al at the cucumber-js team, 
Following is the protractor-config.ts :
    cucumberOpts: {
         strict: true,
        //format: ['message:cucumber-messages.ndjson,"html"],
        format: ['json:reports/results.json', 'node_modules/@cucumber/pretty-formatter'],
               //'format-options' : '{  "colorsEnabled": true }',
        //'no-colors' : true,
        require: ['features/StepDefinitions/*.js'],
        ignoreUncaughtExceptions: true
    },

1) As a fairly new user to protractor/cucumber , unable to get the migrated pretty formatter working, error is as below if the above commented lines for color are entered: 
E/launcher - Error: TypeError: Cannot read property 'colorsEnabled' of undefined ( same error with no-colors option)

2) If the 'quotes' are removed from JSON: 'format-options' : {  "colorsEnabled": true }, then get:
E/launcher - Error: Error: --format-options passed invalid JSON: Unexpected token o in JSON at position 1: [object Object]

3) also have the original formatters been moved as they appear to be non functional: i.e. in protractor-config.ts
format: ['message:cucumber-messages.ndjson,"html"],
E/launcher - Error: Error: Cannot find module 'C:\Users\jsmith\cucumber\auto\git_stuff\work_dir\html'
E/launcher - Error: Error: Cannot find module 'C:\Users\jsmith\cucumber\auto\git_stuff\work_dir\message'

Environment: protractor 7.0.0, protractor-cucumber-framework 6.2.1, @cucumber/cucumber 7.0.0, @cucumber/pretty-formatter 1.0.0-alpha.0
Your guidance would be much appreciated. Thanks

**Comment by jbpros** [comment]
Hey @gituser-21. I don't have much recent experience with Protractor. Could you share an example of a setup that reproduces this? 

Not sure this is relevant, and I'm not sure if the config is supposed to be JSON, but if that's the case be careful with the quotes: they need ot be double quotes in JSON.

What's certain is that `{ format-options: ...` is definitely not valid JSON nor JavaScript, the dash is not allowed if you don't use quotes.

**Comment by gituser-21** [comment]
Hi @jbpros, Thanks for getting back. It's basically the same as above:
Environment: protractor 7.0.0, protractor-cucumber-framework 6.2.1, @cucumber/cucumber 7.0.0, @cucumber/pretty-formatter 1.0.0-alpha.0

Issue1)   E/launcher - Error: TypeError: Cannot read property 'colorsEnabled' of undefined  at new PrettyFormatter 

CONFIG: protractor-config.ts

exports.config = {
    directConnect: true,
    framework: custom,
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    getPageTimeout: 180000,
    allScriptsTimeout: 50000,

    capabilities: {
        "browserName": "chrome",
        unexpectedAlertBehaviour: 'accept',
        shardTestFiles: true,
        maxInstances: 2,
        chromeOptions: {
            args: [
               // "--headless",
                "--no-sandbox",
                "--disable-gpu",
                "--disable-dev-shm-usage"
            ]
        }
    },
    baseUrl: "https://test-sight.com",
    plugins: [{
        package: 'protractor-multiple-cucumber-html-reporter-plugin',
        options: {
            automaticallyGenerateReport: true,
            removeExistingJsonReportFile: true
        }
    }],

    suites: {
         createANA: properties.get('createANAFeaturePath'),
         createBBP: [properties.get("createBBPFeaturePath")],
}
cucumberOpts: {
strict: true,
format: ['json:reports/results.json', 'node_modules/@cucumber/pretty-formatter'],
require: ['features/StepDefinitions/*.js'],
ignoreUncaughtExceptions: true

onPrepare: function () {
        browser.manage().window().setSize(1600, 1050);
        browser.waitForAngularEnabled(false);
    }
},

Trace1:
> ws_cucumber_test@1.1.0 prestuff C:\Users\jsmith\cucumber\dir2
> tsc

> ws_cucumber_test@1.1.0 stuff C:\Users\jsmith\cucumber\dir2
> protractor protractor.config.js --suite "createANA"

[16:41:26] I/launcher - Running 1 instances of WebDriver
[16:41:26] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:52887/devtools/browser/fa7244c0-687e-4f03-9e69-7efd0756cdf2
[11260:1352:0209/164127.911:ERROR:device_event_log_impl.cc(211)] [16:41:27.911] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[11260:1352:0209/164127.924:ERROR:device_event_log_impl.cc(211)] [16:41:27.924] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[11260:1352:0209/164127.934:ERROR:device_event_log_impl.cc(211)] [16:41:27.934] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[16:41:33] E/launcher - Error: TypeError: Cannot read property 'colorsEnabled' of undefined
    at new PrettyFormatter (C:\Users\jsmith\cucumber\dir2\node_modules\@cucumber\pretty-formatter\src\index.ts:84:35)
    at Function.build (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\formatter\builder.js:44:12)
    at C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\index.js:104:31
    at tryCatcher (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (C:\Users\jsmith\cucumber\dir2\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
[16:41:33] E/launcher - Process exited with error code 100

Issue2) next as per message above add assumed property (with double quotes): 
"format-options" : [ {"colorsEnabled" : true }],

Result2)
[17:09:55] E/launcher - Error: Error: --format-options passed invalid JSON: Unexpected token o in JSON at position 1: [object Object]
    at C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\argv_parser.js:33:15
    at Command.<anonymous> (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\node_modules\commander\index.js:396:13)
    at Command.emit (events.js:315:20)
    at Command.parseOptions (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\node_modules\commander\index.js:751:14)
    at Command.parse (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\node_modules\commander\index.js:456:21)
    at Function.parse (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\argv_parser.js:81:13)
    at getExpandedArgv (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\helpers.js:35:28)
    at Cli.getConfiguration (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\index.js:52:58)
    at Cli.run (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\index.js:125:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[17:09:55] E/launcher - Process exited with error code 100

Issue3) next, remove/comment out above property 'format-options' and try with:  "no-colors" : true,

Result3) Same as in result1
[17:11:45] E/launcher - Error: TypeError: Cannot read property 'colorsEnabled' of undefined

Issue3a) try with         "colorsEnabled" : "true", 
Same result as issue1) [17:45:43] E/launcher - Error: TypeError: Cannot read property 'colorsEnabled' of undefined

Issue4) now try with original plain format options for report files -  html or message (without pretty formatter) --- this is property related to @cucumber/cucumber itself , not pretty formatter. I do have 2 packages cucumber ^6.0.5 and @cucumber/cucumber ^7.0.0, Even with just single package 7.0.0 installed get error

DevTools listening on ws://127.0.0.1:49939/devtools/browser/634c2e82-59a4-4fc3-90dd-987d5855451f
[17:18:51] E/launcher - Error: Error: Cannot find module 'C:\Users\jsmith\cucumber\dir2\message'
Require stack:
- C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\formatter\builder.js
- C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\index.js
- C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\index.js
- C:\Users\jsmith\cucumber\dir2\node_modules\protractor-cucumber-framework\lib\cucumberLoader.js
- C:\Users\jsmith\cucumber\dir2\node_modules\protractor-cucumber-framework\index.js
- C:\Users\jsmith\cucumber\dir2\node_modules\protractor\built\runner.js
- C:\Users\jsmith\cucumber\dir2\node_modules\protractor\built\launcher.js
- C:\Users\jsmith\cucumber\dir2\node_modules\protractor\built\cli.js
- C:\Users\jsmith\cucumber\dir2\node_modules\protractor\bin\protractor
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Function.loadCustomFormatter (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\formatter\builder.js:110:29)
    at Function.getConstructorByType (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\formatter\builder.js:77:33)
    at Function.build (C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\formatter\builder.js:38:40)
    at C:\Users\jsmith\cucumber\dir2\node_modules\cucumber\lib\cli\index.js:104:31
[17:18:51] E/launcher - Process exited with error code 100
npm ERR! code ELIFECYCLE

found some related issues, perhaps?  https://github.com/cucumber/cucumber-js/issues/1551
https://github.com/cucumber/cucumber-js/issues/910

**Comment by davidjgoss** [comment]
Going to close this now as the formatter is not the issue here - you should seek support from the protractor-cucumber-framework project.

Only thing I'd say is from the stack trace there, the old `cucumber` package is what's running, so probably an update of protractor-cucumber-framework is needed.
