### ISSUE TITLE
Breaks with @cucumber/cucumber v7.2.0

### ISSUE THREAD

**Issue by asze** [cucumber/cucumber-js-pretty-formatter#2]
After upgrading `@cucumber/cucumber` to v7.2.0, this formatter breaks with a stacktrace that looks like the following:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/formatter/helpers' is not defined by "exports" in ./node_modules/@cucumber/cucumber/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (./node_modules/@cucumber/pretty-formatter/src/index.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at legacy (./node_modules/@cucumber/cucumber/lib/importers.js:10:55)
```

Looks like deep imports are no longer allowed following cucumber/cucumber-js#1589.

**Comment by asze** [comment]
Looks like `@cucumber/cucumber` v7.2.1 reverts the regression. All good here!
